### ISSUE TITLE
oasys bombs because shadow3

### ISSUE THREAD

**Issue by srio** [oasys-kit/shadow3#33]
In some LINUX installations of OASYS (using miniconda) the OASYS application bombs when running a system contaning source and at least one optical element: 

![image](https://user-images.githubusercontent.com/502315/40350834-370b42ba-5dab-11e8-8d77-cc399b95ba99.png)

```
Exit from SETSOUR
Call to IMREF
Exit from IMREF
Call to OPTAXIS
At line 416 of file src/fortran/stringio.f90
Internal Error: get_unit(): Bad internal unit KIND
```

The problem is related to using an old compiler for creating the shadow3 binaries. 

For example, this is bad: 
```
gurb:/nobackup/srio/OASYS1.1 % gfortran --version
GNU Fortran (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING
```

This is good: 
```
chac:~/OASYS1/shadow3/dist % gfortran --version
GNU Fortran (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
```

Quick solution: 
overwrite the installation with a working compiled version (wheel). For example: 

```
pip install http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.5.30-cp36-cp36m-linux_x86_64.whl--upgrade
```

Developer solution: 

Install shadow3 in your system, compile it and test it: 

```
git clone http://github.com/oasys-kit/shadow3 
cd shadow3
python setup.py clean build
pip install . --upgrade
cd tests
python test_lens.py
```
If this fails, you need to upgrade your compiler. 

Note that simple "pip install shadow3" may fail as it may download sources and build them in your system.

**Comment by srio** [comment]
It looks that the problem is not the compiler: 
it bombs with python 3.6.5
it works with python 3.6.3!!!

**Comment by srio** [comment]
Indeed, the problem is more subtil. 

It is not depending neither on the python nor the conda version. 

The problem is with conda: there is a conflict with the fortran libraries installed by conda when installing xraylib.
 
If one preforms the installation of shadow3 with conda  is OK. 

If one installs xraylib and then shadow3, there is no compilation problem but bombs when copying strings in fortran. In fact it bombs in something like this, which is completely legal and correct in fortran: 

```
   integer(kind=ski)  :: length2
   character(len=80)  :: SLENGTH

   length2 = 2
   write(slength,fmt=*) length2


```

The solution is may be to avoid to install xraylib using conda. 

I confess I am not a fan of conda, I spent three days in this!!

**Comment by tschoonj** [comment]
Hi Manolo,

The problem here is not the xraylib conda package but numpy, which is responsible for dragging in the libgfortran shared library.

For this problem to stop occurring, I recommend you compile shadow3 with the gfortran compiler from conda, not the one provided by the system.

Hope this helps!

Tom
