### ISSUE TITLE
cannot update the adds-ons on Jan.26, 2020

### ISSUE THREAD

**Issue by gwax09** [oasys-kit/shadow3#38]
I am trying to upgrade the adds-on to OASYS-kit. The message reminds to upgrade pip. After upgrading the pip to the latest, the OASYS-kit still refuses to upgrade and keep warning.
Please help me out,
Thanks

**Comment by lucarebuffi** [comment]
Dear gwax09, your message is so lacking of details that it is impossible to help you out.

1 - are your installing Oasys or are you updating the add-ons from the Add-ons form?
2 - which operative system are you using (Windows, Linux or Mac?)
3 - please send screenshots or text containing the WHOLE error message you are receiving.

**Comment by gwax09** [comment]
Thanks, Luca.
I am using the Ubuntu 18.4.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
For the snapshots

![Add-on](https://user-images.githubusercontent.com/38352351/73147722-b9ffc880-40f3-11ea-8bea-ef7a0f6dddc0.png)
![Error](https://user-images.githubusercontent.com/38352351/73147723-ba985f00-40f3-11ea-8843-6d77df8eb10e.png)
![Errormessage](https://user-images.githubusercontent.com/38352351/73147724-ba985f00-40f3-11ea-8ba2-146ad55f164f.png)
![pip2](https://user-images.githubusercontent.com/38352351/73147707-a94f5280-40f3-11ea-8c0e-6d3b79639c0c.png)
![pip3](https://user-images.githubusercontent.com/38352351/73147726-bbc98c00-40f3-11ea-9024-2b8157d29f58.png)
![Upgrading](https://user-images.githubusercontent.com/38352351/73147730-bc622280-40f3-11ea-95dd-bc37757be7dc.png)

**Comment by lucarebuffi** [comment]
Dear gwax09,

pip has nothing to do with the problem you are facing. I strongly suggest you try reinstalling Oasys with the new installation scripts. Please do the following:


1 - remove the folder oasys1env in the home directory of your user. In the same directory there should be the folder containing the old installation scripts, please remove it as well.

2 - Reinstall Oasys by following the instructions here: https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Linux

**Comment by gwax09** [comment]
Thanks, Luca. Brilliant idea!
I reinstalled successfully!

**Comment by lucarebuffi** [comment]
so far so good.
