### ISSUE TITLE
fatal error LNK1136: invalid or corrupt file

### ISSUE THREAD

**Issue by rtash92** [oasys-kit/shadow3#45]
Hello,

I am trying to install ShadowOui using OASYS and have encountered the following error when attempting to install shadow3:

"build\temp.win-amd64-3.8\shadow3c.lib : fatal error LNK1136: invalid or corrupt file"

From what I can tell, it appears like there is an issue with my C++ compiler that I am unaware how to fix. I am currently using VisualStudio build tools with the following installed:

MSVC v142 - VS 2019 C++ x64/86 build tools
Windows 10 SDK (10.0.18362.0) - but have also tried using v 10.0.14393.0
Windows Universal CRT SDK

I am using a Windows 10 machine with MinGW-W64 GCC-7.3.0 for the fortran compiler and the miniconda installer with python 3.8.5. I have also tried using other GCC versions (8.1, 6.4) but the newer version gives a different error like has been described in other issues.

Here is the full output during installation just in case it provides any useful information.
[shadow3_lnk1136.txt](https://github.com/oasys-kit/shadow3/files/5649495/shadow3_lnk1136.txt)

**Comment by srio** [comment]
Hello, 
It is not clear for me if you tried to install it from sources or using pip
we recommend to install the Oasys version using pip. It is installed when you install Oasys. It installs the binaries that work well (at least up to now) in windows10. 

If you want to build from sources, you need an old gfortran compiler (version 8 does not work: https://github.com/oasys-kit/shadow3/issues/35  but I see you use version 7... ).

Please let me know if the pip-installed binary version does not work.

**Comment by rtash92** [comment]
Hello,

Sorry for the confusion. I installed Oasys using the .bat files as suggested in the wiki page and have been attempting to install shadowoui / shadow3 using pip. I am getting these errors during pip installation.

During installation of oasys, I had to downgrade to the previous version of numpy due to "an error in windows runtime" (more info [here](url)).

During pip installation, I first got an error saying I needed Visual Basic 14.0 or later. After installing build tools, I got another error saying "object has no attribute compiler_f90" which was fixed by installing a gfortran compiler. The issue I am getting now is after installing both compilers after seeing those errors.

I wonder if all of these are somehow connected?

Thank you!

**Comment by srio** [comment]
Hello, 
I suggest to restart from scratch the Oasys installation. Clean (delete) before the previous installation that creates the folder c:\<home>\miniconda3. The installer will create a new miniconda installation so you do not have to update compilers nor change installed versions. Usually the binaries we have in the shadow3 installer work well for all PCs, but may be your one has something new. Let me know then where it crashes. 
If you want to reinstall (or retry) shadow3 after that, be sure to use the Oasys-python
c:\<home>\miniconda3\python.exe -m pip install --upgrade shadow3
Sorry for this mess!

**Comment by rtash92** [comment]
Hello,

I uninstalled all compilers and miniconda at attempts of a fresh install. 

Oasys installs just fine (first installing numpy 1.19.3 through pip to avoid current issues with 1.19.4 and windows), but when trying to install shadowoui / shadow3 I get an error saying I need Visual C++ 14.0 or greater. I get this error both when trying to install from the Oasys GUI and from miniconda using c:<home>\miniconda3\python.exe -m pip install --upgrade shadow3.

No problem with the errors, this has been a good learning experience for me (I only know how to code in python and not very well).

Thanks!

**Comment by srio** [comment]
OK, I see that for any reason the binary pip distribution is not good for your platform and pip ties to build it from sources. And of course it fails. To build shadow3 in windows is a pain. In fact, we use the version compiled time ago. And I do not have anymore the system I used to it will take time to build it again...

I suggest to try to force the installation of the binary doing (after activating your Oasys conda environment): 

pip install https://files.pythonhosted.org/packages/01/18/124205b5e0f41b872ff4ba4f1dc5d48de6b8c6e9c7985a1a6d5ea209e3ce/shadow3-18.5.30-cp37-cp37m-win_amd64.whl 

Let me know... Otherwise I will try to recompile everything and let you know the procedure... but it will take some time.

**Comment by rtash92** [comment]
I noticed you linked a wheel for python 3.7 and I was using python 3.8. I switched my version and everything installed just fine from pip. Thank you so much for the help!

**Comment by lucarebuffi** [comment]
Indeed. We are not supporting python3.8, yet.

**Comment by srio** [comment]
I'm happy this issue was solve. We will look in the future to new versions.
