### ISSUE TITLE
License for this repo

### ISSUE THREAD

**Issue by mrakitin** [oasys-kit/shadow3#50]
Hello @srio, what is the license for this project? Is it BSD 3-Clause or similar? Could you please kindly add the corresponding license file? Thank you!

**Comment by srio** [comment]
Thanks for the remark. I added it.

**Comment by mrakitin** [comment]
Thank you, @srio! Here is a relevant commit for the reference: https://github.com/oasys-kit/shadow3/commit/d007ae59a2038db4f9275f7bb026bd1b11549e5f.
