### ISSUE TITLE
SI100 produces unrealistic intensity

### ISSUE THREAD

**Issue by avdudchenko** [oasys-kit/shadow3#51]
Hello, 

Trying to simulate simple angles scans in Bragg and Laue configurations for SI100, SI111 and SI220 crystals. 
I have a ligth source (WIggler at 15 kEv with +/- 5ev distribution) connected to plane crystal set up in either Bragg or Lauer configuration. (Shown bellow)

I get expected results for SI111 and SI220, but for SI100 the intensity values explode (e.g. I get intensity >10000 at any incidence angle including computed Bragg/Laue configuration.  

The crystal data is generated using Bragg tool. Is this a known issue? Or is there a solution/workaround I should try?

Configuration:
![image](https://user-images.githubusercontent.com/33663878/138570435-1538c163-26e3-41a3-b03b-a4f7fa4cda31.png)

Result for SI100  at bragg angle
![image](https://user-images.githubusercontent.com/33663878/138570466-2e515526-021a-4d32-a659-f8e34b2f88f0.png)

Result for SI111 at bragg angle
![image](https://user-images.githubusercontent.com/33663878/138570477-f2ef0985-73d1-4281-816a-26c2651a8a76.png)

Thank you.

**Comment by srio** [comment]
Si 100 is a forbidden reflection. 
You can see in XOPPY/Crystal that the Structire factos is zero. 

You should get about zero, however, there are some singular values when calculating the reflectivity so it gets something very big instead of something very small. But the case is not realistic.
