### ISSUE TITLE
simulation of paraboloid mirror

### ISSUE THREAD

**Issue by Lizetttt** [oasys-kit/shadow3#52]
It comes some confusions when I go through my simulation of paraboloid mirror. I will list them below.

1.	The mirror
I want the mirror could collimate the divergent beam in horizontal orientation, so I set  the O.E. orientation angle of the mirror to 90 degrees.
When I changed the angular divergence X(+ & -) of the source into a considerable value (e.g. 1 rad), the imaging results showed two light spots. 
I wonder whether two symmetrical mirrors have actually been set in the paraboloid module?
2.	The orientation of center light
An obvious question showed up If my presume above were true: I set up the incident angle, the source plane distance and the paraboloid parameter so that I can define the point “A” at which the center light acts with the parabolic collection mirror. Then I set up the dimensions of the mirror(X,Y half widths), so that I have construct the shape of one pair of dual parabolic mirrors. After I finish these steps, the another one pair of the dual parabolic mirrors would be created by symmetry through the axis of the parabola. 
Here comes the question: If I choose a gaussian source, the center light of the source is the ray that initiated from the center of gaussian spot to the point “A” which firstly defines the parabolic mirror that I construct, In the design of a spectrometer. It is hoped that the center light coincides with the parabolic mirrors symmetrical axis, the situation above makes the gaussian source plot somewhat asymmetric for parabolic symmetry axis. 
What could I attempt to make the center light coincide with the parabolic symmetry axis? 
![dual mirror ](https://user-images.githubusercontent.com/94047761/141262717-868823da-8517-46fe-9193-ae53857ab8ef.jpg)
3.	The movement of the source
To be honest, I am so confused about those items in source movement. It seems that I could construct a polar coordinate system which the origin is at point “A”, then I could freely change the position of the source in the space. What confuse me is the item below.
What would happen if I change those offsets in O.E. and SOURCE reference frames. after I have set up the angle of incidence, distance from O.E. and Z-rotation, i.e. whether there is a priority between the change of incident arm and angle with the change of the reference frame? 
![setting](https://user-images.githubusercontent.com/94047761/141262769-1ac73f85-fbb4-4ede-b84f-d5fae130c5a3.jpg)

 
   In my spectrometer layout design, I hope to make all the symmetry axes of meridional-oriental O.E. (e.g. focus mirror, grating) are coincident with the symmetry axis of the dual parabolic mirrors and the center light when the source is stable. However in the reference frame logic of SHADOW, when the source movement is taken into consideration, the layout seems to be so strange. In other words, I do not want my layout to be influenced by the movement of source. What parameter should I set extra to achieve my goal?
 
![layout](https://user-images.githubusercontent.com/94047761/141262828-5a0ba6f0-a2a2-4246-b7f2-06b16d596496.jpg)

Thank you so much!
[parabolic collimate mirror.zip](https://github.com/oasys-kit/shadow3/files/7518867/parabolic.collimate.mirror.zip)

**Comment by srio** [comment]
>1- I wonder whether two symmetrical mirrors have actually been set in the paraboloid module?
Actually yes. Shadow calculates the intercept with the infinite surface. Then, from the two posible solutions of the conic equation, it takes the closer one. 

2 > Here comes the question: If I choose a gaussian source, the center light of the source is the ray that initiated from the center of gaussian spot to the point “A” which firstly defines the parabolic mirror that I construct, In the design of a spectrometer. It is hoped that the center light coincides with the parabolic mirrors symmetrical axis, the situation above makes the gaussian source plot somewhat asymmetric for parabolic symmetry axis.
What could I attempt to make the center light coincide with the parabolic symmetry axis?

This is difficult. I have no answer.
I tried the parabola with the beam in normal incidence (0 degrees with the normal) and placing the source at the parabola focus. You get something collimated, but the footprint on the mirror is not good (shadow takes the closer solution and we want the farther one). 

3 - The application of the movements has a sequential order (I do not remember, I should look to the code). I suggest not to move source and OE at the same time. 
Note that the source and OE movements are set to see the beam displacement therefore the origins (optical axis) still corresponds to the non-deviated beam. 


What I suggest is to simulate only one reflection (not the two reflections at the same time) and rotate the element (and translate it) to see the effect of misalignment. 

Sorry for not being more helpful!
