### ISSUE TITLE
BRAGG standalone use

### ISSUE THREAD

**Issue by shadow19820714** [oasys-kit/shadow3#53]
Some great examples already given in the src/examples.  And by using  the functions of the C API we can create personalized scripts.  But how can we use the subroutines in the shadow_preprocessors, like BRAGG or PreSURFACE in our C scripts？  
This may be an old question already asked by others before, but it still keeps making me puzzled when I use the example01.c to simulate a Crystal diffraction.  
 Thanks,  if there could be any tips~

**Comment by srio** [comment]
In fact, as far as I know, the C API is not used directly by our users. Most of then use the Oasys environment and the python scripts. There is no C preprocessors not C-binding.  Just a remind  that a file created by the fortran preprocessor or the python oasys tools can be used for your calculations.
