### ISSUE TITLE
choosing the torus pole location

### ISSUE THREAD

**Issue by srio** [oasys-kit/shadow3#56]
On 8/13/22 1:41 AM, Samuel Gleason wrote:

Dear Manuel,

I have a small question about choosing the torus pole location.
I attach a file with two mirrors that represent different pieces of a bicycle-tire torus.
The first mirror is the 'bottom' of the tire, that is, a concave/concave surface.
The second mirror is the 'top' of the tire, that is, a convex/convex surface.

I've rotated the second mirror 180 degrees about its sagittal axis, expecting that this would make the two mirrors equivalent.
Instead, the beam now intersects the rotated mirror far away from the pole.

Are you able to explain why this is the case?
I asked Ruben Reininger, but he was also confused.

Thanks very much!
Sam Geason

![torus_cartoon](https://user-images.githubusercontent.com/502315/186423196-6b4d0873-f430-4dd9-acd2-0c742f19fa17.png)

[torus_question.zip](https://github.com/oasys-kit/shadow3/files/9416169/torus_question.zip)

**Comment by srio** [comment]
Dear Sam,

Sorry for the lot of time I took to look at that.

As a rule of thumb, the o.e. movements are supposed to be small to check tolerances. Otherwise, you may find unexpected results, as you got.

I made some tests. I first made a pencil beam (zero cross section and very small divergence) to check the center. When you increase the X rotation, is like if you change the incident angle. When you arrive to an angle of 17 deg you see the change as the grazing incidence becomes 0. Then increasing goes well up to 90+17. Checking the angles before and after this value, you see the interception changes from negative Y to positive Y, meaning that shadow changes from one solution to another of the quartic equation (i.e. it is looking at another part of the curved surface). Therefore, when you rotate 180 deg shadow looks to another part of the surface.

We found this problem on several occasions. Shadow automatically selects one solution of the two in conics or 4 solutions in toroids. Unfortunately, there is no way to control that.

I hope this gives some light to the problem.

Best regards,

Manuel

PS: If you do not mind, I copied your question to the shadow3 issues: https://github.com/oasys-kit/shadow3/issues/56

**Comment by lucarebuffi** [comment]
I communicated with Sam in private last week.

**Comment by slgleason** [comment]
Thank you both very much for your help.
The context was attempting to consistently select the interior surface of a self-intersecting torus, such as the one on the right-hand side of these plots.
I could usually access the surface I wanted using various OE rotations, but not every time.

Per Manuel's suggestion, I followed the 'thermal bump' tutorial to project the desired figure onto a plane mirror, which worked great.

Thanks again,
Sam

![torus_comparison](https://user-images.githubusercontent.com/111999550/186458775-c5e2e5c7-c64a-4d94-bf29-69dac24dfc19.png)
![torus_3d](https://user-images.githubusercontent.com/111999550/186458467-769e4d96-8882-4ec0-b7ee-c453a5b9ff66.png)
