### ISSUE TITLE
reflectivity with graphite 002

### ISSUE THREAD

**Issue by srio** [oasys-kit/shadow3#57]
On 8/25/22 10:28 AM, Yu Xiaojiang wrote:
> Dear Manuel
>
> I test the reflectivity with graphite 002 and Si 111 for two configurations, finding the angles on the plane crystals of graphite are same in two configures, but reflectivity is difference, NOT expected.
>
> For Si 111, angles are different, so the different reflectivity is just expected.
>
> Do you think the problem is from Shadow code?
>
> Please see the setup in the workspace attached (please check in CRYSTAL widget, graphite is chosen, my crystal list in the xraylib may be different from you).
>
> Best regards
> Xiaojian
![Graphite](https://user-images.githubusercontent.com/502315/186618932-0070d373-4312-44c7-9d83-52c76c2c3bf3.png)
[graphite_reflectivity.zip](https://github.com/oasys-kit/shadow3/files/9423064/graphite_reflectivity.zip)

**Comment by srio** [comment]
The results are similar for Graphite and Si, I mean you see that shadow autosetting sets the crystal to the "corrected Bragg angle" but using external profile, the crystal is set to the "uncorrected" Bragg angle. The latter is done by the interface, and cannot be done better. 
![image](https://user-images.githubusercontent.com/502315/186620777-468bde92-367b-44d9-8fbb-2812d30e64eb.png)

For getting the angles that are really used in the calculation, you should see the o.e. "info", and here you see that for Graphite  they are indeed (slightly!) different:
![image](https://user-images.githubusercontent.com/502315/186620158-6796b7be-e0da-46fd-92c8-27e900df6f14.png)

The numerical value you see in the interface is autofilled by the interface and corresponds to the Bragg angle and not to the corrected Bragg angle. It is only an indication (I accept that it could be confusing...).

Does this answers the question? 

regards, Manuel

**Comment by 91902078** [comment]
I use corrected bragg angle by choosing  th-th bragg (corrected) in crystal widget for 2nd graphite config, I expect both curves almost overlapped in the center position, but not expect to get different 
![graphite corrected](https://user-images.githubusercontent.com/81464221/186632742-b5c04567-b65c-441f-a613-73644a761292.png)

**Comment by 91902078** [comment]
I use my version Shadow, in above setting, get overlapped in central position
![graphite corrected-my](https://user-images.githubusercontent.com/81464221/186634050-b3110a81-3fde-428e-86a1-8611326ccf6a.png)

my version has minor change in CRYSTAL subroutine in shadow_kernel.f90
![CRYSTAL_func](https://user-images.githubusercontent.com/81464221/186635160-e5be79a3-20b2-46aa-be36-7aa403fefc9d.png)

**Comment by 91902078** [comment]
For Si 111, if use same corrected bragg angle in CRYSTAL widget in 2nd configure, also get overlapped in central position
![Si111 corrected](https://user-images.githubusercontent.com/81464221/186638189-6ea6a90f-6b3a-4a1f-96f4-3c9cfa7dea6b.png)

**Comment by srio** [comment]
I am not sure if I understood correctly the problem. 

If I use autosetting in shadow, the histogram should be centered at zero (because it calculates the Bragg corrected angle)
This happens with Graphite for the 3 ways to calculate the preprocessor file (v1, v2-dabax, v2-xraylib):
![image](https://user-images.githubusercontent.com/502315/186640148-3c8a5cb4-c96c-4e02-9c68-c0eb18a840ff.png)

I get the same centered histogram if I do not use auto-setting and copy/paste the  angles:
   Incidence Ang.     81.123721 deg
   Reflection Ang.    81.123721 deg

Up to here, it looks OK for me. 

If you use external profile from xoppy/crystal, the shadow uses the angle defined in the "position" tab. This is changed when you have the xoppy/crystal widget connected and you "run" it. It is set at the uncorrected Bragg angle, so typically you see the resulting histogram not centered. But this is external to shadow3. 

Another interesting point is your change in fortran. It looks at a first view that indeed you corrected a bug. But this is only affecting the v1 preprocessor. It is strange that I see no major differences in my comparison (see fig) from v1 (buggy?) to v2 (correct?). This I do not understand and would need a more careful look...

**Comment by 91902078** [comment]
If Atomic mass not add to f0, then real part of refrac index is very small, delta is ~1, so the corrected  Bragg angle theta_B is equal to uncorrectec theta (graze), but this is almost not affect the value of Darwin width, so histogram always centered around theta_B (angle 0), and with similar profile. But if one uses auto angle setting in plane crystal, the return corrected angle from shadow will be not correct (values shown in gray field), please compare this  value with that inside the output tab of crystal widget.

________________________________

**Comment by srio** [comment]
Yes, it is a bug. I will fix and upgrade shadow3 soon (in 1 or 2 days). 
Thanks a lot for reporting the problem and giving the solution...

**Comment by srio** [comment]
Fixed in shadow3 22.8.25 shadowOui 1.5.202

**Comment by 91902078** [comment]
Thanks!

**Comment by 91902078** [comment]
Test successfully!
