### ISSUE TITLE
Storing the output data

### ISSUE THREAD

**Issue by Lizetttt** [oasys-kit/shadow3#59]
Dear Srio:

It seems there is something wrong with my Outlook that I cant receive the note of your response. I am so sorry about that.

The problem of parabolic collimate mirror seems to be an indifferent case to us. Now we are focusing on the dispersion direction. 

In our design, X-ray whose intensity obeys the Gaussian distribution, will be emitted from the source, then it will interact with cylindrical focusing mirror and varied line spacing plane grating, then we can get a spot of light which is probably Gaussian morphology at the point of emission. However, because of the high-order aberration from the optical elements, such as spherical aberration, there will be a distortion at the bottom of the spot so that the intensity of the spot will not be a perfect Gaussian distribution.
 

![image](https://user-images.githubusercontent.com/94047761/193226590-48fd090f-266c-4bf4-a1cb-b9698a50908d.png)

there is a significant widening of the bottom of the spot, since we haven’t done spherical aberration correction

What I want to do is to dig out the specific data of the intensity distribution of the outgoing light spot. But I fail to find the way to save the data rather than picture.
So, here is my question: Whether could I store specific intensity data?If could, what should I do to store the data locally?

Thank you so much!

**Comment by srio** [comment]
Hi, 
there are many ways to get he intensity out of the results. For example: 
![image](https://user-images.githubusercontent.com/502315/193785661-0120787f-e318-493e-a776-e1bcf8063ea7.png)

1) attach a plotxy widget and select to write results to a file. All the plot data is in a hdf5 file that you can access with your own tools. You can see it with the hdf5 viewer. 

![image](https://user-images.githubusercontent.com/502315/193785866-77afcb69-3e18-47a0-9f40-09107055df8a.png)


2) You can extract the data programmatically. An example is in the attached script that you can copy in the script widget:
```
beam = in_object_1._beam

# beam.rays contains all the shadow info
print(beam.rays.shape)

# for intensity plot, we make an histogram
# see https://github.com/oasys-kit/shadow3/blob/master/Shadow/ShadowLibExtensions.py
tkt = beam.histo2(1,2,nolost=1,ref=23)

# the resulting dictionary contains the info
for key in tkt.keys():
    print(key)
    
from srxraylib.plot.gol import plot_image
plot_image(tkt['histogram'],tkt['bin_h_center'],tkt['bin_v_center'],aspect='auto')


```

**Comment by Lizetttt** [comment]
Thank you so much Srio, I'll try it next work day. I want to make this issue open for a while so that I could communicate with you if something wouldn't work.

**Comment by Lizetttt** [comment]
Hi Srio, I have successfully saved the data, thank you for the help!

**Comment by srio** [comment]
You're welcomed!
