### ISSUE TITLE
Syntax error in ShadowLibExtensions.py

### ISSUE THREAD

**Issue by lucarebuffi** [oasys-kit/shadow3#64]
Line 1561:

                    txt += 'Johansson radius                         %f %s\n'(self.R_JOHANSSON,self.unit())

a percentage symbol is missing, modify in:

                    txt += 'Johansson radius                         %f %s\n'%(self.R_JOHANSSON,self.unit())

**Comment by srio** [comment]
This is fixed. Thanks!
I recreated all wheels for shadow3 version 23.9.19
I realigned ShadowOUI with this new shadow3. In addition, it contains other fixes done in 2023 on Johansson crystals that were not updated in ShadowOUI.  

I tested in linux+windows. Hopefully, mac is also OK. Let me know if there are problems (I do not think so).
