### ISSUE TITLE
How to change the propagation direction of source in shadow3 of OASYS Software ?

### ISSUE THREAD

**Issue by 11Harshad** [oasys-kit/shadow3#65]
Hello Sir,

I am working on surface which was created by assuming source propagation direction along the z-axes but in shadow source propagation direction is along the y-axes so what changes i need to make in the source properties in OASYS software so source propagation direction will be along the z-axes?

For your reference sir @srio I have attached schematic figure of setup 
![Screenshot at 2023-09-19 11-55-53](https://github.com/oasys-kit/shadow3/assets/96642577/90bab4a3-8bc3-4747-afd4-04011b532d14)
  
thanks sir

**Comment by srio** [comment]
Hello, 
In Shadow you cannot change the reference frames. You have to adapt to them. 

If you create an external surface, it has to be of the form z(x,y) (x: width, y: length, z: height), centered in the middle, and all in the same units (your Oasys user units). An example is in the tutorial example 21: https://github.com/oasys-kit/ShadowOui-Tutorial/blob/master/ex21_thermalbump.ows

Hope this helps!

**Comment by 11Harshad** [comment]
Okay thank you sir
