### ISSUE TITLE
 ellipsoid mirror setup

### ISSUE THREAD

**Issue by Lizetttt** [oasys-kit/shadow3#66]
Hello Srio:
     So sorry to disturb you but I have a trouble setting up the ellipsoid mirror.
     In the interface of ellipsoid mirror, at "surface shape" unit, two choices of setup have been given : In the on hand, I can enter the object distance, image distance and incidence angle, then the program can automatically generate optical surface for me (internal/calculated) , in the other hand, I can directly  enter the semi-major axis and semi-minor axis (external/user defined).
    Here comes the question: In the "external" model, SHADOW needs a parameter called "Angle of MajAx and Pole", I guess it’s the angle between optical element center normal and the major axis of the ellipsoid mirror. However, when I substitute the calculated value of the angle, the output is very different from the previous "internal" setting.
![image](https://github.com/oasys-kit/shadow3/assets/94047761/770848a8-dbed-4672-a9f3-6d8d689be3b7)
![image](https://github.com/oasys-kit/shadow3/assets/94047761/810496c0-af37-4b85-96d1-6e3040d0d7aa)
    I would be very grateful if you could provide a specific geometric description of "Angle of MajAx and Pole".

**Comment by srio** [comment]
Hi.
The angle is this "delta": 
![image](https://github.com/oasys-kit/shadow3/assets/502315/f38a7fbf-4f14-48a7-826e-34367546b5a3)

Some draft hand-notes and equations can be found here: 
https://github.com/srio/shadow3-docs/blob/master/doc/conics.pdf

Hope this helps.

**Comment by Lizetttt** [comment]
It actually works. 
Thank you so much Srio.

**Comment by srio** [comment]
You're welcome.
