### ISSUE TITLE
link to Shadow user guide is broken

### ISSUE THREAD

**Issue by bruhwiler** [oasys-kit/shadow3#67]
This link is no longer working, https://www.esrf.fr/pub/scisoft/shadow3/Shadow3Primer.pdf

**Comment by lucarebuffi** [comment]
[Shadow3Primer.pdf](https://github.com/oasys-kit/shadow3/files/14842480/Shadow3Primer.pdf)

**Comment by bruhwiler** [comment]
Thank you, @lucarebuffi

**Comment by lucarebuffi** [comment]
Anytime

**Comment by srio** [comment]
Thanks David, thanks Luca. I updated the link. Cheers, M
