### ISSUE TITLE
Optical component configuration issues

### ISSUE THREAD

**Issue by kuikui350** [oasys-kit/shadow3#68]
The outgoing rays of the point light source are reflected through the plane mirror at a certain angle of incidence, is it possible to configure the plane mirror reflection point not to be at the geometric center of the plane mirror?

**Comment by srio** [comment]
The optical axis goes from the center of the source to the center of the mirror. The distances and anges are referred to these points. Therefore it is not possible to define the orientation angles of the mirror at a position outside its center.
